---
deployment:
  tasks:
    - export DEPLOYPATH=/home/himalay6/public_html/
    - /bin/cp /home/himalay6/repositories/task-manager/index.html $DEPLOYPATH
    - /bin/cp /home/himalay6/repositories/task-manager/style.css $DEPLOYPATH
